/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_tencent_tnn_demo_video_VideoGrade */

#ifndef _Included_com_tencent_tnn_demo_video_VideoGrade
#define _Included_com_tencent_tnn_demo_video_VideoGrade

#include "VideoGradeInterface.h"
#include "../../../../../../../../../../../../../Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
#include "../../helper_jni.h"
#include "../../../../../../../../../../../../../Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/android/bitmap.h"

#ifdef __cplusplus
extern "C" {
#endif

void makeVideoGradeOption(std::shared_ptr<TNN_NS::VideoGradeOption> &option,
                          std::string &lib_path, std::string &proto_content,
                          std::string &model_content);


/*
 * Class:     com_tencent_tnn_demo_video_VideoGrade
 * Method:    initTNN
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_tnn_demo_video_VideoGrade_initTNN
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_tencent_tnn_demo_video_VideoGrade
 * Method:    deinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tencent_tnn_demo_video_VideoGrade_deinit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
